# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Unitymetrics

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.13'

    - name: Install dependencies Gounity
      run: |
          go version
          go get -u github.com/equelin/gounity
    - name: Install dependencies Logrus
      run: |  
          go version
          go get -u golang.org/x/sys/unix
          go get -u github.com/sirupsen/logrus
          
    - name: Install
      run: go install 

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go build -v ./...
